#+title: Readme
#+author: c6es6r

* Über Dieses Projekt
Dieses Projekt wird im Rahmen einer Projekt Arbeit in der Schule erstellt.
Ab dem 12.03.2024 ist es jedem freigestellt, sich an der Entwicklung zu beteiligen.

* Nutzung
** Dependencies
Das einzige benötigte Paket ist *pygame*.

** Ausführen
Das Projekt kann einfach mit dem *make* Befehl ausgeführt werden.
Falls dieser nicht funktioniert, kann der folgende Befehl genutzt werden:
#+begin_src shell
python3 src/main.py
#+end_src

Gegebenenfalls muss die *3* weggelassen werden.

** Aufräumen
Um die beim spielen erzeugten Cache-Dateien zu entfernen, einfach folgenden Befehl nutzen.
#+begin_src shell
make clean
#+end_src

** Spielen
Die einzige Taste die zum Spiel gebraucht wird ist die *SPACE*-Taste. Mit ihr springt der Spieler nach oben.
Ziel des Spiels ist es den anfliegenden Gegnern auszuweichen. Für jeden Gegner, dem ausgewichen wurde, gibt es einen Punkt.
Mit der Zeit bewegen sich die Gegner immer schneller, was das Spiel somit auch immer schwieriger macht.
